ODDS_API_KEY="e7605f6e5d1006713e11663c0105a022"

SUPABASE_URL="https://libyvlfgawsowwtxdogt.supabase.co"

SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpYnl2bGZnYXdzb3d3dHhkb2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0MzIyNzAsImV4cCI6MjA5NDAwODI3MH0.RqXJV4QKJqrrvK-1bKdRl0V861VihGsVsD5UGGiTafI"